apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- path: pg_backup.yaml
- path: postgres-service-patch.yaml

configMapGenerator:
- literals:
  - NATS_SERVER=nats://my-nats.production.svc.cluster.local:4222
  name: broadcaster-config

namePrefix: prod-
images:
- name: todo-backend
  newName: us-central1-docker.pkg.dev/master-coder-465618-q6/my-repository/todo-backend
  newTag: v1.0.0
