apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: exercises
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sh", "-c", "sleep 3600"]
      stdin: true
      tty: true
