apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-application
  template:
    metadata:
      labels:
        app: pong-application
    spec:
      containers:
        - name: pong-application
          image: bidhe1/pong_application
