apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-application
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-application
  template:
    metadata:
      labels:
        app: pong-application
    spec:
      # volumes:
      #   - name: shared-logs
      #     persistentVolumeClaim:
      #       claimName: shared-logs-pvc
      containers:
        - name: pong-application
          image: bidhe1/pong_application:latest
          ports:
            - containerPort: 3000
          # volumeMounts:
          #   - name: shared-logs
          #     mountPath: /app/logs
