apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-application
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-application
  template:
    metadata:
      labels:
        app: pong-application
    spec:
      initContainers:
        - name: check-db
          image: postgres:9.6
          command: [
              "sh",
              "-c",
              "until pg_isready -h postgres-service -p 5432;
              do echo waiting for database; sleep 2; done;",
            ]
      containers:
        - name: pong-application
          image: bidhe1/pong_application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 7
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
