apiVersion: v1
kind: Service
metadata:
  name: pong-application-lb
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: pong-application
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
