# this is base64 encode so user name password is actually is : postgres
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: exercises
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM= # postgres
