apiVersion: v1
kind: Service
metadata:
  name: pong-application-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: pong-application
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
