apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: NodePort
  selector:
    app: todoapp
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1235
      targetPort: 3000
