apiVersion: v1
kind: Service
metadata:
  name: wikipedia-server-service
  labels:
    app: wikipedia-server
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: wikipedia-server
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: wikipedia-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wikipedia-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingress/wikipedia-gateway # Corrected to use namespace/name format
  http:
    - route:
        - destination:
            host: wikipedia-server-service
            port:
              number: 80
