apiVersion: batch/v1
kind: Job
metadata:
  name: gcs-test-upload
  namespace: project
spec:
  template:
    spec:
      containers:
        - name: gcs-upload
          image: google/cloud-sdk:alpine
          command:
            - /bin/sh
            - -c
            - |
              gcloud auth activate-service-account --key-file=/secrets/gcs/key.json
              echo "Hello from Kubernetes at $(date)" > /tmp/hi.txt
              gsutil cp /tmp/hi.txt gs://my-unique-postgres-backup-bucket/hi.txt
              echo "File uploaded successfully!"
          volumeMounts:
            - name: gcs-secret
              mountPath: "/secrets/gcs"
              readOnly: true
      volumes:
        - name: gcs-secret
          secret:
            secretName: gcs-secret
      restartPolicy: Never
  backoffLimit: 1
