apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/secret.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/todo_job.yaml

images:
  - name: PROJECT/IMAGE
    newName: placeholder #bidhe1/todo-backend:latest ok
