apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TheGrinderAC/devops-with-kubernetes
    path: project-gitops-config-repo/argocd/applications
    targetRevision: HEAD
    directory:
      recurse: false
      include: "*-staging.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
