apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - ../broadcaster/kustomization.yaml
images:
  - name: PROJECT/IMAGE
    newName: placeholder # bidhe1/todo_app:latest <-- before using the gcp artifacts registary

