apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - name: hello
          image: bidhe1/hello:1
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
  traffic:
    - latestRevision: true
      percent: 50
    - latestRevision: false
      percent: 50
      revisionName: hello-00001
