apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: writer
          image: bidhe1/log_output_writer:latest
          volumeMounts:
            - name: shared-logs
              mountPath: /app/logs
        - name: reader
          image: bidhe1/log_output_reader:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-logs
              mountPath: /app/logs
      volumes:
        - name: shared-logs
          emptyDir: {}
