apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
  namespace: exercises
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 1234
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: pong-application-svc
                port:
                  number: 2345
          # - path: /adminer # not using it right now
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: adminer-service
          #       port:
          #         number: 3456
