apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- gateway.yaml
- routes.yaml
- service.yaml
images:
- name: log_output
  newName: bidhe1/log_output
  newTag: 3044054c90995bb221b7f39ed034f486c0442345
