apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/postgres-secret.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
