apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml

namePrefix: prod-
images:
- name: broadcaster
  newName: us-central1-docker.pkg.dev/master-coder-465618-q6/my-repository/broadcaster
  newTag: v1.0.0
