apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: broadcaster-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TheGrinderAC/devops-with-kubernetes
    path: project-gitops-config-repo/apps/brodcaster/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
