apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoapp-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TheGrinderAC/devops-with-kubernetes
    path: project-gitops-config-repo/apps/todo-app/overlays/production
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
