# This file(secret.yaml) contains a Kubernetes Secret for PostgreSQL credentials.
# All values are base64-encoded. For example, 'cG9zdGdyZXM=' decodes to 'postgres'.
# Do NOT commit this file with real credentials. Use secret.enc.yaml (encrypted with sops) for production.
# To apply the secret, decrypt secret.enc.yaml and use that instead.
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: project
type: Opaque
data:
    #ENC[AES256_GCM,data:rKRWK6kCl17S,iv:JWl4CBNfNiBnE56T6+aON2rHLMEDWIIQDqnjGTCQteE=,tag:kAsTAb+Sa5zePKUFuR6/0A==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:DifQvSQtobwaSMo7,iv:DYHfd16w7V00mD3bS93c4pANcmTnn6lWuOp3qs1KBAk=,tag:Q6T4kWAIpCgU79eOFH4mjA==,type:str]
    #ENC[AES256_GCM,data:ktIVvEf9Cige,iv:0b27xDmc2iyEHuvrvw6IuJy0xl4XCmJfbfrRrYQz3Rs=,tag:d5bBMtha2xd1/u9NXZe6Dw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:nUuDUSJeGD6bX9N1,iv:dxdRF/1mKNrOeegI7gYYpaPH9yo97UbW1ZF9USP0378=,tag:UrzZghk3l3dEuMloZRVbAw==,type:str]
    #ENC[AES256_GCM,data:dClpBvCL/Ri+SRcbnpYJtz0=,iv:gL9819U9YuZKGbQOrPnWEh7LlEQ0QQZAm7T3128i2TQ=,tag:QmxkEt9GItl/PiWZc5ghXQ==,type:comment]
    POSTGRES_HOST: ENC[AES256_GCM,data:z2rnPwfcBwJaXLFojn6FF0hHmPCUfyho,iv:yLBwXBZQe2sSy3wUsdF4h1PzBAvcvqh9R2akyxTsI8g=,tag:nyVLq+Em+M1cPHuHWBIRWg==,type:str]
sops:
    age:
        - recipient: age1w5dhtytpgus86qd832zzcrfg4t7qngya6gelgzyxkqvlk7rrpywquunuy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN2RVelBDeDRBTlpMcGNa
            WUdwZWI0UWlFUlFTSGovVk5WbDBlR2k4aURzCmVQZ0lxbFpERk1Ld2lNVjlQcWpB
            YW0wVWI5citVV2dtcWVYV2dDMVFzelEKLS0tIDEwUVZlZ255TlhObFovVy90TlV6
            U2t1UWRjcG1uSGxvSEJMbzFDMTBzTmMKSL4xlxmsb1poIIBjvZ3N6Oa2+VRiYgme
            MrugQdCLFRER00uLHmVEZqo0s3ORF6vKd8v6uGnkEzPW4REwc8SRaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T01:09:10Z"
    mac: ENC[AES256_GCM,data:7Z+A5lepGjkGM3zQJxYG2R7fIp9OaQ/oFGn8ksdsjzvJg4lqWUAug+QBOUm6Tr1F91QqdC24CoBXnUPAB8qpwVglhZlbBMzsCajg9NpJ80r7LIwP1IMLlvRRC3Lz0BwXz9gqJavnqiyZRNcbLPCdnCYi9XDNh9gV2HZdzN4sQE4=,iv:ZZ0PpcwPlB/WmdQMPhTw9MgoxBrPuH8ar2cpbnTSg70=,tag:e9UNcQqGWrhEktQ8RFh2SA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.10.2
