apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todobackend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
