apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namePrefix: prod-
patches:
- path: configmap.yaml
  target:
    kind: ConfigMap
    name: app-config
images:
- name: todo-app
  newName: us-central1-docker.pkg.dev/master-coder-465618-q6/my-repository/todo-app
  newTag: v1.0.0
