apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pong
  namespace: exercises
spec:
  template:
    spec:
      containers:
        - name: pong
          image: bidhe1/pong_application:v1.2
          env:
            - name: POSTGRES_HOST
              value: "postgres-service.exercises"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
