name: Cleanup Environment on Branch Deletion

on:
  delete

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: us-central1-a

jobs:
  cleanup:
    name: Cleanup Environment
    runs-on: ubuntu-latest
    if: github.event.ref != 'main' && github.event.ref_type == 'branch'

    steps:
      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Delete Kubernetes Namespace
        run: |
          BRANCH_NAME=${{ github.event.ref }}
          echo "Deleting namespace: $BRANCH_NAME"
          kubectl delete namespace $BRANCH_NAME --ignore-not-found=true
