name: pong-application Build and Publish Application

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
    paths:
      - "pong-application/**"

permissions:
  contents: write

jobs:
  build-publish:
    name: Pong_Application Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish backend
        run: |
          docker build --file pong-application/dockerfile --tag "bidhe1/pong_application:${GITHUB_SHA}" pong-application
          docker push "bidhe1/pong_application:${GITHUB_SHA}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kustomization.yaml with new image
        run: |
          cd pong-application
          kustomize edit set image pong_application=bidhe1/pong_application:${GITHUB_SHA}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "New version released ${{ github.sha }}"
          file_pattern: "pong-application/kustomization.yaml"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
